const mongoose = require('mongoose')

const resumeSchema = new mongoose.Schema({
  userId: {type: mongoose.Schema.Types.ObjectId, ref: 'users', required: true},
  firstName: {type: String, required: true}, 
  lastName: {type: String, required: true},
  email: {type: String, required: true}, 
  phoneNumber: {type: String, required: true}, 
  address: {type: String}, 
  gitHub: {type: String}, 
  linkedIn: {type: String}, 
  twitter: {type: String}, 
  facebook: {type: String}, 
  instagram: {type: String}, 
  college: {type: String, required: true}, 
  schoolDate1: {type: String, required: true}, 
  cgpa: {type: String, required: true}, 
  qualification: {type: String, required: true}, 
  degree1: {type: String, required: true}, 
  schoolName: {type: String}, 
  schoolDate2: {type: String}, 
  percentage: {type: String}, 
  schoolQualification: {type: String}, 
  degree2: {type: String},
  skill1: {type: String, required: true}, 
  skill2: {type: String, required: true}, 
  skill3: {type: String}, 
  skill4: {type: String}, 
  interest1: {type: String, required: true}, 
  interest2: {type: String, required: true}, 
  interest3: {type: String}, 
  interest4: {type: String}, 
  careerObjective: {type: String, required: true}, 
  workshop1: {type: String, required: true}, 
  workshop2: {type: String}, 
  title1: {type: String, required: true}, 
  link1: {type: String, required: true}, 
  description1: {type: String, required: true}, 
  title2: {type: String}, 
  link2: {type: String}, 
  description2: {type: String}, 
  fullName: {type: String, required: true}, 
  gender: {type: String, required: true}, 
  status: {type: String}, 
  nationality: {type: String, required: true}, 
  dateOfBirth: {type: String, required: true}, 
  languageProficiency: {type: String, required: true}, 
  picture: {type: String, required: true}
  },
  { minimize: false },
  { timestamps: true }
)

module.exports = mongoose.model('resume', resumeSchema)
